### ISSUE TITLE
DaVinci Resolve to Multiple CDLs Request

### ISSUE THREAD

**Issue by bsales** [shidarin/cdl_convert#38]
First, is there a way to export per-shot .cdl files instead of a single CDL bundle when there are multiple entries in the source? I know the cc files can do that, but I get an error in Color Finesse (in AE) with those. Color Finesse can load .cdl files, but only sees the first item if there are many. I ended up cutting and pasting the entries, which worked, but wasn't ideal.

Also, I had s situation with the Resolve ALE export where there were two clips with the same name. The script kinda choked on that. I don't see any reason this needs to be addressed, it's an odd one. Just wanted to mention it.

The only other thing that I had to deal with was path and filenames with spaces in them. I know that's a common issue with utility programs and we should be better about file naming here. Still haven't developed good habits yet.

Generally, I think it's a fantastic tool. Thanks again for developing it.

**Comment by shidarin** [comment]
Have done the single file collection export (Each color decision in an ALE/CDL/CCC will export to it's own CCC or CDL) in: d84aa22b46d767cf7503105be0e43b248266a156 & 87b9b63947a35990b1aa912940dac820927f49b1

This is slated to be in the 0.8 release, along with the fix to spacers & duplicate shot IDs.

**Comment by shidarin** [comment]
Regarding the spaces... I'm not getting any errors when I convert files with spaces in them. They're allowed as a character in names.

```
Alethkar:CDL Tests sean$ cdl_convert SalesTests\ CC.ale -o ccc
Destination directory /Users/sean/Desktop/CDL Tests/converted does not exist.
Creating destination directory.
Writing collection to /Users/sean/Desktop/CDL Tests/converted/SalesTests CC.ccc
```

They do need to have character escapes in the terminal shell though. I know you're working on an Applescript wrapper, could the wrapper not be escaping the filenames properly when it goes to the shell command?

So you can't just type `Desktop/MyFiles/Avengers Delivery 13/test1.cdl`, you'd have to write: `Desktop/MyFiles/Avengers\ Delivery\ 13/test1.cdl`. Apologies if you already knew this, just not sure what error you're getting.

**Comment by shidarin** [comment]
Okay! Non-unique IDs are now A-okay provided you are not giving the script the '--halt' flag. It will now append a 001 (for the second instance), 002, and so on, for each duplicate ID field it comes across. 

Work done in 1e32ad36e5125b5ea265f120f742b49076bde821

**Comment by bsales** [comment]
Sean,

Thanks so much for working on these issues. I’m in NY right now helping with CHE’s move to a larger office-space here. I’ll be back in LA next week and have a chance to try out your updates.

Maybe I was wrong about the spaces in filename issue. Does it work with both quoted paths as well as back-slash style ones?

Anyway.. thanks again and I’ll check it out next week.

Take Care,
Brian

**Comment by shidarin** [comment]
Just tried it with quoted paths and it does work still. We can open a specific issue if you try it and still find it giving you an error next week. For now, I'm marking this issue (single-cc export of collection files) complete with the 0.8 release, which is on Pypi now and installable with pip.
