### ISSUE TITLE
Please support CMX EDL with ASC comments (standard)

### ISSUE THREAD

**Issue by jicabrera** [shidarin/cdl_convert#39]
Hey there!

I'm surprised the tool doesn't parse CMX EDL files. These files are very common among post-production houses and very standard when sending data across facilities. here is an example:

TITLE: /mnt/Avid02/cdls/20150204/makeup_test_cdl.edl

001  RR0010.bg1.SRC V     C        00:00:31:05 00:00:46:09 01:00:00:00 01:00:15:04  
*ASC_SOP (1.763262 1.776213 2.034658)(0.064582 -0.026949 -0.091332)(1.191500 1.191500 1.191500)
*ASC_SAT 0.723500

002  BC1010.bg1.SRC V     C        00:00:47:14 00:00:57:03 01:00:20:04 01:00:29:17  
*ASC_SOP (1.685540 1.464669 1.478464)(0.015455 -0.009279 -0.018970)(1.191500 1.191500 1.191500)
*ASC_SAT 0.687500

003  XA1410.bg1.SRC V     C        00:01:02:00 00:01:11:19 01:00:14:17 01:00:14:12  
*ASC_SOP (1.698344 1.600991 1.707363)(-0.004576 -0.022940 0.000044)(1.400000 1.400000 1.400000)
*ASC_SAT 0.723500

**Comment by jicabrera** [comment]
It would be awesome if the software could create one .ccc file per shot!
Thanks!!

**Comment by shidarin** [comment]
One .ccc per shot should be possible with the --single flag. If that's not working it's a separate bug. (Could also be I've worded the --help text ambiguously/poorly!)

CMX EDL should also be working, I'll check out why the tool is failing here.

Thank you!

**Comment by jicabrera** [comment]
It would be truly great if the CMX EDL was working. I have hundred of shots
in this format... If you need any more sample files, just say the word!

Thanks,

---
*Juan Ignacio Cabrera*
*Colorist & Stereographer*
*SGO Mistika Specialist*
+1 (818) 370-5849
IMDb <http://www.imdb.com/name/nm3043942>

**Comment by shidarin** [comment]
I'm pretty sure I remembered wrong this morning- I got some CMX sample files but never got around to adding support in!

I'll take a look tonight and see if I can't get it working quickly. 

Can you zip up some samples and send them over? The more samples I have the better probability it'll work on everything.

sean@grenadehop.com

**Comment by gregcotten** [comment]
Any updates on this?

**Comment by shidarin** [comment]
Pushing something shortly onto develop that parses CMX. Tests not updated yet.

**Comment by shidarin** [comment]
Just pushed [feature/parse_cmx](https://github.com/shidarin/cdl_convert/tree/feature/parse_cmx) which has CMX parsing in response to Juan's request in April. It worked for him, but there's no tests yet so it hasn't been pushed to develop or master yet.

Adding tests.

**Comment by shidarin** [comment]
Merged feature/parse_cmx into develop. Added Issue #45 for the tracking of adding unittests.

Updated docs and version number to alpha2 of 0.9.
