### ISSUE TITLE
tests failing on windows 10, py 2..7.6

### ISSUE THREAD

**Issue by Ahuge** [shidarin/cdl_convert#51]
Hey Sean, I'm working on adding support for Nuke OCIOCDLTransform nodes and I noticed that your test_cdl_convert and test_cdl tests seem to be failing for me.

I am also getting test_classes.TestColorCorrection.testDetermineDest failing for me as well. for the last one, it appears to be the abspath you are doing on line 1917 that is adding my drive letter which is making it different from the actual path. I'm not sure if cc/determine_dest is supposed to be relative or absolute but it currently appears to be relative.

The console is here: http://pastebin.com/psq2whLX

I am sorta new to testing so perhaps I am running these tests from the wrong location (I am running the **init**.py in tests to start the testing).

If I disable the two modules for testing cdl and _fix_ the test_classes one, everything else seems to work.

Let me know if I am a twit and doing something wrong
- Alex

**Comment by shidarin** [comment]
Most of these look like windows related errors- it's been a while since I ran the tests on windows so I'm not surprised- the CI server also runs them on Linux, so it doesn't catch windows related pathing errors.

It's unlikely you're doing anything wrong.

What version of python are you using? 2.7 for Nuke 8-9? 2.6 for 7?

 -Sean Wallitsch

**Comment by Ahuge** [comment]
I'm python 2.7.6
I'm not using the nuke python module in my parsing. You can see it action here: https://github.com/shidarin/cdl_convert/compare/master...Ahuge:Nuke-OCIO-CDL-Transform

Ill assume that those are ok to fail until I do some specific testing with them. If there is a problem I might update the tests as well.
