### ISSUE TITLE
Convert Resolve ALE 

### ISSUE THREAD

**Issue by Sashmo** [shidarin/cdl_convert#54]
Hi,

were trying to convert ALE Files comming from a DaVinci Resolve System. 
We have successfully installed cdl_convert (v0.9) via pip, but we are not able to convert the ALE from Resolve. 

The script fails and we get this error: 

`Traceback (most recent call last):
  File "/usr/local/bin/cdl_convert", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/cdl_convert/cdl_convert.py", line 222, in main
    color_decisions = parse.parse_file(filepath, filetype_in)
  File "/usr/local/lib/python2.7/site-packages/cdl_convert/parse.py", line 792, in parse_file
    return INPUT_FORMATS[filetype](filepath)
  File "/usr/local/lib/python2.7/site-packages/cdl_convert/parse.py", line 157, in parse_ale
    sat = cdl_data[ale_indexes['ASC_SAT']]
KeyError: 'ASC_SAT'`

 I will attach a demo ALE. Maybe you have a clue why we get the error.
Many Thanks.

Best,
Sascha

[ALE.zip](https://github.com/shidarin/cdl_convert/files/208120/ALE.zip)

**Comment by shidarin** [comment]
Thanks for the report and the sample Sascha. Your ALE looks perfect to me. I'll be checking this out today.

**Comment by shidarin** [comment]
Pushing out a release of `0.9.1` to pip with this fix now. Thanks for the bug report and sample file.

**Comment by shidarin** [comment]
`0.9.2` is on pypi (pip) now for download, which includes this fix. I ended up making a few more changes, so I ended up not pushing `0.9.1` to pypi.

**Comment by Sashmo** [comment]
Hi, 
thank you for your effort! We will download 0.9.2 today.
Thanks!
